language: python
python:
  - "2.7"
  - "3.4" 
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - coverage run test_calculator.py
before_install:
  - pip install codecov
after_success:
  - codecov

